-- users table
INSERT INTO users (name, email, password) VALUES ('Margalo', 'mrenish0@webs.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u');
INSERT INTO users (name, email, password) VALUES ('Jodee', 'jagastina1@ovh.net', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u');
INSERT INTO users (name, email, password) VALUES ('Aidan', 'atruin2@mapy.cz', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u');
INSERT INTO users (name, email, password) VALUES ('Hobard', 'hcossor3@baidu.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u');
INSERT INTO users (name, email, password) VALUES ('Zak', 'zpatrick4@bizjournals.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u');
INSERT INTO users (name, email, password) VALUES ('Fayette', 'ftutchener5@homestead.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u');
INSERT INTO users (name, email, password) VALUES ('Merilee', 'mtorn6@paypal.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u');
INSERT INTO users (name, email, password) VALUES ('Annecorinne', 'aeynald7@constantcontact.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u');
INSERT INTO users (name, email, password) VALUES ('Brittani', 'bphidgin8@time.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u');
INSERT INTO users (name, email, password) VALUES ('Woody', 'wdegoey9@ca.gov', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u');
INSERT INTO users (name, email, password) VALUES ('Cynthea', 'ctruswella@about.me', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u');
INSERT INTO users (name, email, password) VALUES ('Verine', 'vjoshb@scribd.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u');
INSERT INTO users (name, email, password) VALUES ('Linn', 'lrebanksc@nymag.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u');
INSERT INTO users (name, email, password) VALUES ('Efren', 'emartonfid@intel.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u');
INSERT INTO users (name, email, password) VALUES ('Nalani', 'nbalstonee@jigsy.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u');

-- properties table
INSERT INTO properties (owner_id, title, description, thumbnail_photo_url, cover_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, country, street, city, province, post_code, active) VALUES (1, 'Pleo Muc', 'description', 'http://dummyimage.com/206x.png/dddddd/000000', 'http://dummyimage.com/117x.png/5fa2dd/ffffff', 92687, 1, 31, 47, 'Indonesia', 'Sloan', 'Rimpakgede', 'Texas', '78235', false);
INSERT INTO properties (owner_id, title, description, thumbnail_photo_url, cover_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, country, street, city, province, post_code, active) VALUES (2, 'Loratadine', 'description', 'http://dummyimage.com/151x.png/ff4444/ffffff', 'http://dummyimage.com/246x.png/dddddd/000000', 42039, 49, 73, 55, 'China', 'John Wall', 'Xiangfeng', 'Michigan', '48107', false);
INSERT INTO properties (owner_id, title, description, thumbnail_photo_url, cover_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, country, street, city, province, post_code, active) VALUES (3, 'GRx Dyne', 'description', 'http://dummyimage.com/100x.png/dddddd/000000', 'http://dummyimage.com/204x.png/ff4444/ffffff', 64347, 26, 23, 26, 'Philippines', 'Westerfield', 'Purac', 'California', '95973', true);
INSERT INTO properties (owner_id, title, description, thumbnail_photo_url, cover_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, country, street, city, province, post_code, active) VALUES (4, 'Tizanidine', 'description', 'http://dummyimage.com/134x.png/ff4444/ffffff', 'http://dummyimage.com/239x.png/cc0000/ffffff', 55500, 53, 81, 79, 'Poland', 'Alpine', 'Ursynów', 'Kansas', '66105', false);
INSERT INTO properties (owner_id, title, description, thumbnail_photo_url, cover_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, country, street, city, province, post_code, active) VALUES (5, 'Hydrogen Peroxide', 'description', 'http://dummyimage.com/180x.png/cc0000/ffffff', 'http://dummyimage.com/245x.png/5fa2dd/ffffff', 82752, 34, 79, 6, 'China', 'Hovde', 'Matang', 'Florida', '34643', false);
INSERT INTO properties (owner_id, title, description, thumbnail_photo_url, cover_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, country, street, city, province, post_code, active) VALUES (6, 'Nifedipine', 'description', 'http://dummyimage.com/245x.png/5fa2dd/ffffff', 'http://dummyimage.com/250x.png/dddddd/000000', 94366, 92, 23, 52, 'Russia', 'School', 'Pesochnoye', 'New York', '11231', true);
INSERT INTO properties (owner_id, title, description, thumbnail_photo_url, cover_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, country, street, city, province, post_code, active) VALUES (7, 'Nystatin', 'description', 'http://dummyimage.com/163x.png/dddddd/000000', 'http://dummyimage.com/149x.png/5fa2dd/ffffff', 39478, 29, 43, 87, 'Thailand', 'Mitchell', 'Krasae Sin', 'Virginia', '23208', false);
INSERT INTO properties (owner_id, title, description, thumbnail_photo_url, cover_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, country, street, city, province, post_code, active) VALUES (8, 'Atenolol and Chlorthalidone', 'description', 'http://dummyimage.com/127x.png/5fa2dd/ffffff', 'http://dummyimage.com/126x.png/5fa2dd/ffffff', 14076, 29, 64, 79, 'Colombia', 'Iowa', 'Mariquita', 'California', '93407', true);
INSERT INTO properties (owner_id, title, description, thumbnail_photo_url, cover_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, country, street, city, province, post_code, active) VALUES (9, 'Losartan Potassium and Hydrochlorothiazide', 'description', 'http://dummyimage.com/214x.png/cc0000/ffffff', 'http://dummyimage.com/159x.png/5fa2dd/ffffff', 92474, 45, 83, 69, 'China', 'Crescent Oaks', 'Zhangyelu', 'California', '92710', false);
INSERT INTO properties (owner_id, title, description, thumbnail_photo_url, cover_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, country, street, city, province, post_code, active) VALUES (10, 'Octreotide Acetate', 'description', 'http://dummyimage.com/109x.png/ff4444/ffffff', 'http://dummyimage.com/114x.png/cc0000/ffffff', 65483, 22, 53, 94, 'Russia', 'Pennsylvania', 'Chashnikovo', 'Pennsylvania', '15235', true);
INSERT INTO properties (owner_id, title, description, thumbnail_photo_url, cover_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, country, street, city, province, post_code, active) VALUES (11, 'nitetime cold and flu', 'description', 'http://dummyimage.com/196x.png/dddddd/000000', 'http://dummyimage.com/235x.png/cc0000/ffffff', 23167, 6, 61, 33, 'Portugal', 'Rigney', 'Vessada', 'District of Columbia', '20380', true);
INSERT INTO properties (owner_id, title, description, thumbnail_photo_url, cover_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, country, street, city, province, post_code, active) VALUES (12, 'Diastat', 'description', 'http://dummyimage.com/224x.png/dddddd/000000', 'http://dummyimage.com/226x.png/ff4444/ffffff', 37130, 68, 68, 86, 'China', 'Northland', 'Chengdong', 'Michigan', '49048', true);
INSERT INTO properties (owner_id, title, description, thumbnail_photo_url, cover_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, country, street, city, province, post_code, active) VALUES (13, 'Artificial Tears', 'description', 'http://dummyimage.com/195x.png/dddddd/000000', 'http://dummyimage.com/141x.png/5fa2dd/ffffff', 13900, 58, 92, 93, 'Mexico', 'Di Loreto', 'La Mesa', 'New York', '12237', false);
INSERT INTO properties (owner_id, title, description, thumbnail_photo_url, cover_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, country, street, city, province, post_code, active) VALUES (14, 'Feverall', 'description', 'http://dummyimage.com/110x.png/ff4444/ffffff', 'http://dummyimage.com/116x.png/ff4444/ffffff', 84878, 93, 7, 16, 'Colombia', 'Cordelia', 'Miranda', 'California', '95354', false);
INSERT INTO properties (owner_id, title, description, thumbnail_photo_url, cover_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, country, street, city, province, post_code, active) VALUES (15, 'Bupropion Hydrochloride', 'description', 'http://dummyimage.com/170x.png/cc0000/ffffff', 'http://dummyimage.com/111x.png/5fa2dd/ffffff', 89361, 52, 27, 47, 'China', 'Burrows', 'Hongguang', 'California', '92662', true);

-- reservations
INSERT INTO reservations (start_date, end_date, property_id, guest_id) VALUES ('2020-10-28', '2022-06-23', 12, 2);
INSERT INTO reservations (start_date, end_date, property_id, guest_id) VALUES ('2020-11-15', '2021-07-23', 7, 11);
INSERT INTO reservations (start_date, end_date, property_id, guest_id) VALUES ('2019-09-15', '2022-03-23', 15, 11);
INSERT INTO reservations (start_date, end_date, property_id, guest_id) VALUES ('2020-09-17', '2022-12-03', 1, 10);
INSERT INTO reservations (start_date, end_date, property_id, guest_id) VALUES ('2020-08-30', '2022-12-19', 5, 2);
INSERT INTO reservations (start_date, end_date, property_id, guest_id) VALUES ('2020-06-22', '2021-05-24', 9, 10);
INSERT INTO reservations (start_date, end_date, property_id, guest_id) VALUES ('2020-09-07', '2020-12-13', 13, 10);
INSERT INTO reservations (start_date, end_date, property_id, guest_id) VALUES ('2019-10-28', '2021-09-14', 8, 6);
INSERT INTO reservations (start_date, end_date, property_id, guest_id) VALUES ('2019-08-09', '2021-12-15', 4, 6);
INSERT INTO reservations (start_date, end_date, property_id, guest_id) VALUES ('2019-07-21', '2021-05-28', 3, 12);
INSERT INTO reservations (start_date, end_date, property_id, guest_id) VALUES ('2019-12-21', '2022-07-27', 14, 8);
INSERT INTO reservations (start_date, end_date, property_id, guest_id) VALUES ('2020-05-13', '2022-05-24', 10, 10);
INSERT INTO reservations (start_date, end_date, property_id, guest_id) VALUES ('2020-10-11', '2023-01-14', 2, 5);
INSERT INTO reservations (start_date, end_date, property_id, guest_id) VALUES ('2019-09-22', '2021-01-23', 11, 15);
INSERT INTO reservations (start_date, end_date, property_id, guest_id) VALUES ('2019-05-12', '2021-09-26', 6, 15);

-- property reviews
INSERT INTO property_reviews (guest_id, property_id, reservation_id, rating, message) VALUES (2, 8, 15, 4, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.');
INSERT INTO property_reviews (guest_id, property_id, reservation_id, rating, message) VALUES (12, 9, 11, 2, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
INSERT INTO property_reviews (guest_id, property_id, reservation_id, rating, message) VALUES (5, 15, 4, 5, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
INSERT INTO property_reviews (guest_id, property_id, reservation_id, rating, message) VALUES (13, 15, 3, 5, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
INSERT INTO property_reviews (guest_id, property_id, reservation_id, rating, message) VALUES (14, 3, 8, 4, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
INSERT INTO property_reviews (guest_id, property_id, reservation_id, rating, message) VALUES (12, 10, 7, 2, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
INSERT INTO property_reviews (guest_id, property_id, reservation_id, rating, message) VALUES (12, 3, 10, 3, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.');
INSERT INTO property_reviews (guest_id, property_id, reservation_id, rating, message) VALUES (11, 4, 13, 0, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.');
INSERT INTO property_reviews (guest_id, property_id, reservation_id, rating, message) VALUES (13, 1, 7, 3, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
INSERT INTO property_reviews (guest_id, property_id, reservation_id, rating, message) VALUES (2, 9, 15, 1, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.');
INSERT INTO property_reviews (guest_id, property_id, reservation_id, rating, message) VALUES (12, 9, 10, 5, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.');
INSERT INTO property_reviews (guest_id, property_id, reservation_id, rating, message) VALUES (15, 5, 4, 1, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
INSERT INTO property_reviews (guest_id, property_id, reservation_id, rating, message) VALUES (15, 7, 8, 2, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
INSERT INTO property_reviews (guest_id, property_id, reservation_id, rating, message) VALUES (14, 7, 11, 1, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.');
INSERT INTO property_reviews (guest_id, property_id, reservation_id, rating, message) VALUES (15, 14, 8, 4, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.');